### ISSUE TITLE
Flag 1245-119

### ISSUE THREAD

**Issue by bayboos** [MollyMcEvilley/LSASampleCode#903] opened 2022-01-25 14:29 UTC
Hello

We have a client who have one enrollment in the TH project. This client is a child, but also HoH since it’s a single person household. Obviously, such household/enrollment have HHType = 3 - children only. The flag is being triggered because, for a Population = 76, he is being matched with referrence population 76/0 (people who are 18 to 21 years old in all household types) but not with 76/3 (people who are 18 to 21 years old in children only household) - simply because such ref population does not exist. And this does make sense, having an adult person in children only household is not possible. 

Thus, we can assume that the 76/0 match is incorrect; however the query that does the matching (9.4.1) doesn’t seem to be able to exclude this match. The only condition using any age-related values is this: `hhid.ActiveHHType = ph.HHType or ph.HHType = 0` which is correctly excluding the client from household type specific counts (within the relevant population) but does nothing to exclude him from the “all types” count.

The first possible solution that comes to my mind would be to add additional sub-query to check if the hhid.ActiveHHType is within Population-allowed values when ph.HHType = 0 is being used; but such solution 1) should be approved before implementation, 2) with similar approval, may need to be added to other similar queries (especially the ones dealing with age-related populations), and 3) may have a negative impact on the querry’s performance.

Prompt assistance will be highly appreciated. Best regards.

**Comment by OksanaSukhorukova** [comment] 2022-01-26 09:13
Hi @kiadso, @MollyMcEvilley, 
We also have this flag in our upload https://testing.hudhdx2.info/dataset/1553/warning
![image](https://user-images.githubusercontent.com/71442061/151134187-63e54faf-2554-475b-9a55-77de04922248.png)
Looks like this flag is similar to the flag 1246-983 https://github.com/HMIS/LSASampleCode/issues/883

**Comment by MollyMcEvilley** [comment] 2022-01-27 17:57
Current status:  We have a number of issues caused by assigning people multiple ages in a single year and then trying to make point-in-time and report period counts add up neatly.  I can come up with a simple way to address this flag, but I can't come up with a way -- simple or complicated -- to do it without triggering a different set of flags.  Genelle and I are going to talk through this in detail later today and will update after that.

**Comment by kiadso** [comment] 2022-01-27 20:49
After discussing with Molly, we decided to have this reclassified as a Warning also. In Dev's hands now. Will close once changes are pushed.
Thanks!

**Comment by kiadso** [comment] 2022-02-01 17:50
This issue has been removed from the queue to be fixed in today's round of updates since there are sub-flag IDs that should still be classified as an Error. We are working on alternative solutions and will update here when we have more information.

**Comment by jbloescw** [comment] 2022-02-01 18:03
@kiadso Can you state if other flags are part of this?  For example, I'm currently looking into 1246-311 and 1246-551.
2 enrollments over the period but the client has 2 different active ages due to changing age categories during one of the enrollments.  
Not sure if this is roped into the same problem as the other flag but wanted to check.

**Comment by OksanaSukhorukova** [comment] 2022-02-02 10:48
Hi @kiadso,
Unfortunately, I still receive this flag.
My last upload: https://testing.hudhdx2.info/dataset/1621/warning
![image](https://user-images.githubusercontent.com/71442061/152139628-423e3bec-19ac-4a83-b705-03ced59c0291.png)

**Comment by kiadso** [comment] 2022-02-03 17:06
Hi Jeff, yes those two flags definitely fall under the same "clients aging across Household Types" umbrella. Classifying these as Warnings means we recognize the data may be valid. We'll talk more about this in the call today!

**Comment by kiadso** [comment] 2022-02-07 15:55
This is going to be reclassified as a Warning, left as a vendor issue, because there are other subflags that would be considered vendor issues. It's being pushed to Test today, will go to production soon after. I'll leave this open until it's been pushed to production.
Thanks for your patience, all-
Genelle

**Comment by kiadso** [comment] 2022-02-10 13:47
This has been pushed to production. Thanks for your patience-

**Closed as completed by kiadso** 2022-02-10 13:47 UTC
Labels: Data quality flags
