### ISSUE TITLE
Flag 693

### ISSUE THREAD

**Issue by 2008zjqc** [MollyMcEvilley/LSASampleCode#900] opened 2022-01-21 03:39 UTC
Hello,
We have a question with error flag 693, specifically for 693-2 and 693-107, which is 'LSACalculated: Subpopulation is greater than broader population (CoC level)'. 
We have the following case: 
One householdID (say 123) with member of 4: 2/4/2020 -- 3/1/2021
Another household ID (say 456) with member of 5: 5/18/2021 -- 5/25/2021
Both household with same group of people (they all have the same personal IDs), but householdID=456 with a new born. 
The HOH of both householdID is the same person, with DOB 1996-02-22. With as two enrollment date is different, it result in the Entry Age is different. 
Given the above scenario:

In LSACalculated. 9.3 section (Row 53):
Used 'inner join tlsa_HHID hhid on (rp.PopID = 0 or hhid.HouseholdID = pop.HouseholdID)
....
inner join tlsa_Enrollment n on n.HouseholdID = hhid.HouseholdID'

Which use 'HouseholdID' to link, for those households failed the condition won't show up in Row 53. For our test case, householdID 123, HHAdultAge=25 won't show up in the tlsa_CountPops ; HouseholdID 456, HHAdultAge=24 but with LSAProjectType=13, thus, won't meet the condition '(rv.Universe = 11 and hhid.LSAProjectType in (0,1))'.
Therefore for both households, they will not show up in ROW 53. 

In LSACalculated. 9.4 section (Row 55):
Used 'inner join tlsa_CountPops pop on rp.PopID = pop.PopID
	inner join tlsa_Enrollment n on n.PersonalID = pop.PersonalID
...
inner join tlsa_HHID hhid on hhid.HouseholdID = n.HouseholdID '

Which use 'PersonalID' link first with enrollment, then householdID. As in tlsa_CountPops  those 4 personalID can be found and with householdID 123. With such query, with those personalID, it bring two householdID out, both 123 and 456. 

Therefore, this caused the Row 53 count for both individuals and household all less than that for Row 55, which trigged the flag. 

We suggest in Row 55, should be consistent with the linkage condition, as it may use HouseholdID+PersonalID  instead of PersonalID only.

Please take a look and advice. Thanks.

Best,
Chen

**Comment by bayboos** [comment] 2022-01-24 17:41
Hello
We also have some issues with flag 693, specifically 693-212 and 693-338 - both caused by the same person. Just like in the example above, this person has two enrollments with two different household IDs; and it looks like query 9.4.1 makes a mistake when joining tables (tlsa_CountPops is the most relevant) mixing two households together. If needed, I can provide more details for investigation.

Best regards

**Comment by TanyaPieterse** [comment] 2022-01-26 15:44
Hi there,
We have a similar issue Flags 693-254 and 693-395, also caused by the same person.  It is one Enrollment and HouseholdID:

- Mom DOB 09/03/1999 (age 22), Entry Date 01/06/2021 Exit Date 03/25/2021
- Child DOB 02/07/2018 (age 3), Entry Date 01/06/2021 Exit Date 03/25/2021
- Child DOB 02/05/2021 (age 0 newborn),  Entry Date 02/06/2021 Exit Date 03/25/2021

In the LSA Flag, the mom is included in the count of 'all people in the household that was active on January 31st in an ES Project Type in an Adult Child Parenting Youth Household **where the oldest adults is 18-24**'.
BUT
The mom is not included in the count of count of people with the characteristics of 'all people active on January 31st in an ES Project Type in an Adult Child Parenting Youth Household **where the youth is ages 22-24 (Population ID 1277)**'.
The mom is instead counted in the population group **where the youth is ages 18-21 (Population ID 1276)**.  Because the mom’s DOB is 09/03/1999, which means on January 31st she was 21 years old, and would only have been 22 that September 2021.

To me it looks like the one group is counting ages 18-24, but then it is compared to a "split" population group that only looks at ages 22-24.  The above youth is instead included in the group ages 18-21.  I think the Flag should compare the ages 18-24 group to the sum of the other 2 population groups of 18-21 and 22-24 to get the correct picture.

Thanks

**Comment by kiadso** [comment] 2022-01-27 20:57
Hi, this will be reclassified as a Warning as well and I will close this once changes have been pushed.

Thank you Tanya and Chen!

**Comment by kiadso** [comment] 2022-02-01 17:46
Hi Tanya and Chen,

This fix was published to production this morning.

**Closed as completed by kiadso** 2022-02-01 17:46 UTC
Labels: Data quality flags
